export interface SectionCopy {
  aboutEyebrow: string
  whyEyebrow: string
  whyHeadline: string
  servicesLabel: string
  servicesEyebrow: string
  reviewsLabel: string
  reviewsEyebrow: string
  faqEyebrow: string
  faqLabel: string
  ctaHeadline: string
  ctaText: string
  packageLabel: string
  trustBadges: [string, string, string, string]
  whyCards: Array<{ title: string; body: string }>
  reviewSnippets: [string, string, string]
}

export const SECTION_COPY_MAP: Record<string, SectionCopy> = {
  landscaping: {
    aboutEyebrow: 'OUTDOOR ESCAPES',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'PROFESSIONAL & AFFORDABLE',
    reviewsLabel: 'What Our Clients Say',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'KNOW BEFORE YOU START',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Ready to Transform Your Outdoor Space?',
    ctaText: 'Get a free estimate today — no obligation.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Clean Professional Work', 'Experienced Team', 'Locally Owned', 'Satisfaction Guaranteed'],
    whyCards: [
      { title: 'Experienced Professionals', body: 'Our skilled team brings years of hands-on expertise to every project.' },
      { title: 'Reliable & On-Time Service', body: 'We show up when we say we will and get the job done right.' },
      { title: 'Locally Trusted Team', body: 'Rooted in the community, trusted by our neighbors.' },
      { title: 'Satisfaction Guaranteed', body: 'We stand behind every project with a quality guarantee.' },
      { title: 'Custom Design Solutions', body: 'Tailored plans to match your vision and property.' },
      { title: 'Seasonal Expertise', body: 'Year-round care adapted to your climate and needs.' },
    ],
    reviewSnippets: [
      'Absolutely top-notch work. They transformed our property and exceeded every expectation.',
      'Professional, reliable, and the results speak for themselves. Could not be happier.',
      'From start to finish, a wonderful experience. Fair pricing and quality craftsmanship.',
    ],
  },
  roofing: {
    aboutEyebrow: 'LOCAL EXPERTS',
    whyEyebrow: 'THE ADVANTAGE',
    whyHeadline: 'Why Homeowners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE DO',
    reviewsLabel: 'What Our Customers Say',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'GOT QUESTIONS?',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Protect Your Home — Call Us Today',
    ctaText: 'Free inspections and estimates. Licensed and insured.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Free Inspections', 'Storm Damage Experts', 'Warranty Backed'],
    whyCards: [
      { title: 'Trusted Professionals', body: 'Licensed and insured experts you can rely on for every project.' },
      { title: 'Quality Materials', body: 'We use only top-grade materials backed by manufacturer warranties.' },
      { title: 'Clear Communication', body: 'Transparent pricing, timelines, and updates throughout every job.' },
      { title: 'Results That Protect', body: 'Durable workmanship that safeguards your home for years to come.' },
      { title: 'Insurance Claim Help', body: 'We work directly with your insurance company to simplify the process.' },
      { title: 'Emergency Response', body: 'Fast response when storm damage strikes — we are here 24/7.' },
    ],
    reviewSnippets: [
      'Outstanding work. Professional from start to finish, and the results exceeded our expectations.',
      'Fair pricing, great communication, and top-quality craftsmanship. Will use again.',
      'Every step was handled with care. Truly a team of professionals who stand behind their work.',
    ],
  },
  legal: {
    aboutEyebrow: 'OUR STORY',
    whyEyebrow: 'THE STANDARD',
    whyHeadline: 'Why Choose Us',
    servicesLabel: 'Practice Areas',
    servicesEyebrow: 'HOW WE HELP',
    reviewsLabel: 'What People Say',
    reviewsEyebrow: 'CLIENT FEEDBACK',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Get the Representation You Deserve',
    ctaText: 'Schedule a free consultation with our experienced team.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Free Consultation', 'Experienced Attorneys', 'Results-Driven', 'Client Focused'],
    whyCards: [
      { title: 'Local Experience', body: 'Deep roots in the community with genuine local knowledge.' },
      { title: 'Clear Communication', body: 'Transparent updates and honest conversations every step of the way.' },
      { title: 'Consistent Quality', body: 'Reliable results you can count on, time after time.' },
      { title: 'Fast Service', body: 'Quick turnaround without cutting corners on quality.' },
      { title: 'Premium Results', body: 'Exceptional outcomes that exceed expectations.' },
      { title: 'Customer First', body: 'Your satisfaction drives every decision we make.' },
    ],
    reviewSnippets: [
      'An outstanding experience from beginning to end. Truly top-notch representation.',
      'Professional, reliable, and exceeded all of our expectations. Highly recommend.',
      'We could not be happier with the results. Will absolutely be returning.',
    ],
  },
  restaurant: {
    aboutEyebrow: 'OUR KITCHEN',
    whyEyebrow: 'THE EXPERIENCE',
    whyHeadline: 'Why Guests Love Us',
    servicesLabel: 'Our Menu',
    servicesEyebrow: 'WHAT WE SERVE',
    reviewsLabel: 'Guest Reviews',
    reviewsEyebrow: 'WHAT GUESTS SAY',
    faqEyebrow: 'BEFORE YOUR VISIT',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Reserve Your Table Today',
    ctaText: 'Walk-ins welcome. Reservations recommended for parties of 4+.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Fresh Ingredients', 'Made to Order', 'Locally Sourced', 'Family Friendly'],
    whyCards: [
      { title: 'Fresh Ingredients', body: 'We source locally and prepare everything from scratch.' },
      { title: 'Made to Order', body: 'Every dish is crafted fresh when you order it.' },
      { title: 'Consistent Quality', body: 'The same great taste every single visit.' },
      { title: 'Fast Service', body: 'Quality food without the long wait.' },
      { title: 'Premium Quality', body: 'Elevated flavors that keep guests coming back.' },
      { title: 'Customer First', body: 'Your dining experience is our top priority.' },
    ],
    reviewSnippets: [
      'The food was incredible and the atmosphere was perfect. Will be back!',
      'Best meal we have had in a long time. The staff went above and beyond.',
      'Fresh, flavorful, and exactly what we needed. Highly recommend to anyone.',
    ],
  },
  plumbing: {
    aboutEyebrow: 'TRUSTED LOCALLY',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Homeowners Call Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE DO',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Plumbing Problems? Call Now.',
    ctaText: 'Fast, honest plumbing service — available 24/7.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', '24/7 Emergency', 'Upfront Pricing', 'Satisfaction Guaranteed'],
    whyCards: [
      { title: 'Licensed Professionals', body: 'Fully licensed plumbers with years of experience.' },
      { title: 'Upfront Pricing', body: 'No surprises — you know the cost before we start.' },
      { title: 'Same-Day Service', body: 'We respond fast and fix it right the first time.' },
      { title: 'Guaranteed Work', body: 'Every repair is backed by our workmanship guarantee.' },
      { title: 'Emergency Ready', body: 'Available around the clock for urgent plumbing needs.' },
      { title: 'Clean & Courteous', body: 'We treat your home with the same respect as our own.' },
    ],
    reviewSnippets: [
      'Called with an emergency and they were here within the hour. Excellent work.',
      'Fair pricing and the plumber explained everything clearly. Highly recommend.',
      'Fixed our issue quickly and left the area spotless. Will call again.',
    ],
  },
  electrical: {
    aboutEyebrow: 'TRUSTED LOCALLY',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Customers Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE DO',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Electrical Issues? Call Us Today.',
    ctaText: 'Licensed electricians ready to help — residential and commercial.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Code Compliant', 'Upfront Pricing', 'Safety First'],
    whyCards: [
      { title: 'Licensed Electricians', body: 'Fully certified and code-compliant professionals.' },
      { title: 'Safety First', body: 'Every job meets or exceeds local electrical codes.' },
      { title: 'Transparent Pricing', body: 'No hidden fees — clear quotes before work begins.' },
      { title: 'Reliable Service', body: 'On time, every time, with quality you can trust.' },
      { title: 'Residential & Commercial', body: 'We handle jobs of every size and scope.' },
      { title: 'Satisfaction Guaranteed', body: 'We stand behind every wire and connection.' },
    ],
    reviewSnippets: [
      'Responsive, professional, and thorough. The best electrician we have ever hired.',
      'Showed up on time, gave a clear quote, and did great work. Highly recommend.',
      'Fixed a tricky wiring issue that two other electricians could not solve.',
    ],
  },
  hvac: {
    aboutEyebrow: 'COMFORT EXPERTS',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Homeowners Trust Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'HEATING & COOLING',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Stay Comfortable Year-Round',
    ctaText: 'Expert HVAC service — installation, repair, and maintenance.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', '24/7 Emergency', 'Energy Efficient', 'Warranty Backed'],
    whyCards: [
      { title: 'Certified Technicians', body: 'Factory-trained and NATE-certified professionals.' },
      { title: 'Energy Savings', body: 'High-efficiency systems that lower your utility bills.' },
      { title: 'Fast Response', body: 'Same-day service available for urgent breakdowns.' },
      { title: 'Honest Pricing', body: 'Clear quotes with no hidden charges.' },
      { title: 'All Brands Serviced', body: 'We repair and maintain every major HVAC brand.' },
      { title: 'Maintenance Plans', body: 'Preventive care that extends equipment life.' },
    ],
    reviewSnippets: [
      'Installed a new system quickly and the house has never been more comfortable.',
      'Honest, fair pricing, and the technician was extremely knowledgeable.',
      'They fixed our AC in the middle of July within hours. Lifesavers.',
    ],
  },
  dental: {
    aboutEyebrow: 'YOUR SMILE',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Patients Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'DENTAL CARE',
    reviewsLabel: 'Patient Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'PATIENT FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Your Best Smile Starts Here',
    ctaText: 'New patients welcome — schedule your visit today.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Gentle Care', 'Modern Technology', 'Family Friendly', 'Insurance Accepted'],
    whyCards: [
      { title: 'Gentle & Caring', body: 'A comfortable experience for patients of all ages.' },
      { title: 'Modern Technology', body: 'Digital X-rays and advanced treatment tools.' },
      { title: 'Flexible Scheduling', body: 'Evening and weekend appointments available.' },
      { title: 'Insurance Friendly', body: 'We work with most major dental insurance plans.' },
      { title: 'Experienced Team', body: 'Years of training and continuous education.' },
      { title: 'Comprehensive Care', body: 'From cleanings to cosmetic — all under one roof.' },
    ],
    reviewSnippets: [
      'Best dental experience ever. The staff made me feel completely at ease.',
      'Professional, gentle, and thorough. My whole family goes here now.',
      'Finally found a dentist I actually look forward to visiting. Highly recommend.',
    ],
  },
  cleaning: {
    aboutEyebrow: 'SPOTLESS SERVICE',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Clients Trust Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE CLEAN',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'A Cleaner Space Starts Today',
    ctaText: 'Book your first cleaning and see the difference.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Bonded & Insured', 'Eco-Friendly Products', 'Flexible Scheduling', 'Satisfaction Guaranteed'],
    whyCards: [
      { title: 'Trusted Professionals', body: 'Background-checked, bonded, and fully insured.' },
      { title: 'Eco-Friendly Products', body: 'Safe for your family, pets, and the environment.' },
      { title: 'Consistent Quality', body: 'The same thorough clean every single visit.' },
      { title: 'Flexible Plans', body: 'Weekly, bi-weekly, or one-time deep cleans.' },
      { title: 'Attention to Detail', body: 'We clean the spots everyone else misses.' },
      { title: '100% Satisfaction', body: 'Not happy? We will come back and make it right.' },
    ],
    reviewSnippets: [
      'Our house has never looked this clean. Consistent quality every visit.',
      'They pay attention to every detail. Cannot imagine going back to doing it ourselves.',
      'Flexible scheduling and the team is always professional and courteous.',
    ],
  },
  auto: {
    aboutEyebrow: 'UNDER THE HOOD',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Drivers Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'AUTO CARE',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Keep Your Vehicle Running Right',
    ctaText: 'Honest auto repair — no upsells, no surprises.',
    packageLabel: 'Your Website Package',
    trustBadges: ['ASE Certified', 'Honest Pricing', 'All Makes & Models', 'Warranty on Parts'],
    whyCards: [
      { title: 'ASE Certified Mechanics', body: 'Factory-trained technicians you can trust.' },
      { title: 'Transparent Estimates', body: 'You approve the price before we start any work.' },
      { title: 'All Makes & Models', body: 'We service domestic, import, and luxury vehicles.' },
      { title: 'Fast Turnaround', body: 'Most repairs completed same day.' },
      { title: 'Warranty Backed', body: 'Parts and labor backed by written warranty.' },
      { title: 'Honest Advice', body: 'We tell you what you need — nothing more.' },
    ],
    reviewSnippets: [
      'Honest, fair, and fixed it right the first time. My go-to shop from now on.',
      'They explained everything clearly and did not try to upsell me on anything.',
      'Fast turnaround and great price. Highly recommend for any auto repair.',
    ],
  },
  gym: {
    aboutEyebrow: 'OUR MISSION',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Members Choose Us',
    servicesLabel: 'Programs & Classes',
    servicesEyebrow: 'GET MOVING',
    reviewsLabel: 'Member Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'MEMBERSHIP FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Start Your Fitness Journey Today',
    ctaText: 'No long-term contracts. First class free.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Certified Trainers', 'Modern Equipment', 'Flexible Hours', 'Community Driven'],
    whyCards: [
      { title: 'Certified Trainers', body: 'Expert coaches who tailor workouts to your goals.' },
      { title: 'Modern Equipment', body: 'Top-of-the-line machines and free weights.' },
      { title: 'Welcoming Community', body: 'A supportive space for every fitness level.' },
      { title: 'Flexible Hours', body: 'Early morning to late night — work out on your schedule.' },
      { title: 'Group Classes', body: 'High-energy classes to keep you motivated.' },
      { title: 'Results Focused', body: 'Programs designed to deliver real, measurable progress.' },
    ],
    reviewSnippets: [
      'Best gym in town. Great equipment, friendly staff, and clean facility.',
      'The trainers genuinely care about your progress. Totally worth it.',
      'Finally found a gym where I feel welcome and motivated every day.',
    ],
  },
  yoga: {
    aboutEyebrow: 'OUR PRACTICE',
    whyEyebrow: 'THE EXPERIENCE',
    whyHeadline: 'Why Students Love Us',
    servicesLabel: 'Classes & Programs',
    servicesEyebrow: 'FIND YOUR FLOW',
    reviewsLabel: 'Student Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'BEFORE YOUR FIRST CLASS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Find Your Balance',
    ctaText: 'First class free — all levels welcome.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Certified Instructors', 'All Levels Welcome', 'Peaceful Studio', 'Community Focused'],
    whyCards: [
      { title: 'Certified Instructors', body: 'Experienced teachers who guide with care.' },
      { title: 'All Levels Welcome', body: 'From first-timers to advanced practitioners.' },
      { title: 'Peaceful Environment', body: 'A serene space designed for mindful practice.' },
      { title: 'Flexible Schedule', body: 'Morning, evening, and weekend classes available.' },
      { title: 'Community Focused', body: 'A welcoming space where connections grow.' },
      { title: 'Mind & Body', body: 'Holistic practices that nurture the whole person.' },
    ],
    reviewSnippets: [
      'A truly peaceful studio with incredible instructors. My favorite part of the week.',
      'Welcoming from day one. The teachers make every class feel personal.',
      'I have tried many studios — this one is special. The energy is unmatched.',
    ],
  },
  martial_arts: {
    aboutEyebrow: 'OUR DOJO',
    whyEyebrow: 'THE DISCIPLINE',
    whyHeadline: 'Why Students Train With Us',
    servicesLabel: 'Programs',
    servicesEyebrow: 'TRAIN WITH US',
    reviewsLabel: 'Student Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'BEFORE YOU START',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Build Confidence. Build Strength.',
    ctaText: 'First class free — all ages and skill levels.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Certified Instructors', 'Kids & Adults', 'Safe Training', 'Discipline & Respect'],
    whyCards: [
      { title: 'Expert Instructors', body: 'Black belt instructors with decades of experience.' },
      { title: 'All Ages Welcome', body: 'Programs for kids, teens, and adults.' },
      { title: 'Safe Environment', body: 'Structured training with proper supervision.' },
      { title: 'Character Building', body: 'Discipline, respect, and confidence in every class.' },
      { title: 'Competition Ready', body: 'Tournament training for those who want to compete.' },
      { title: 'Flexible Schedule', body: 'Classes throughout the week to fit your life.' },
    ],
    reviewSnippets: [
      'My kids love it here. They are more confident and disciplined than ever.',
      'The instructors are patient, skilled, and genuinely invested in every student.',
      'Best martial arts school in the area. Great for all ages and skill levels.',
    ],
  },
  fitness: {
    aboutEyebrow: 'OUR STUDIO',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Clients Choose Us',
    servicesLabel: 'Our Programs',
    servicesEyebrow: 'GET MOVING',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'GETTING STARTED',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Transform Your Body and Mind',
    ctaText: 'Book your first session — results guaranteed.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Certified Trainers', 'Personalized Plans', 'Small Classes', 'Results Driven'],
    whyCards: [
      { title: 'Personalized Programs', body: 'Custom plans tailored to your body and goals.' },
      { title: 'Small Class Sizes', body: 'Individual attention in every session.' },
      { title: 'Certified Trainers', body: 'Nationally certified fitness professionals.' },
      { title: 'Welcoming Space', body: 'A positive, judgment-free environment for all.' },
      { title: 'Proven Results', body: 'Clients see measurable progress within weeks.' },
      { title: 'Flexible Scheduling', body: 'Morning, midday, and evening sessions available.' },
    ],
    reviewSnippets: [
      'The personalized attention here is unlike any other studio. Real results.',
      'Small classes mean the trainers actually know your name and your goals.',
      'I was intimidated at first but the community here is so welcoming.',
    ],
  },
  painting: {
    aboutEyebrow: 'TRUSTED LOCALLY',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Homeowners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE DO',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Fresh Paint. Fresh Start.',
    ctaText: 'Free color consultation and estimate.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Free Estimates', 'Premium Paints', 'Clean & Courteous'],
    whyCards: [
      { title: 'Licensed Painters', body: 'Fully insured professionals with years of experience.' },
      { title: 'Premium Materials', body: 'Top-quality paints that last for years.' },
      { title: 'Clean Job Sites', body: 'We protect your furniture and clean up completely.' },
      { title: 'On-Time Delivery', body: 'Projects completed on schedule, every time.' },
      { title: 'Color Expertise', body: 'Free color consultation to find the perfect palette.' },
      { title: 'Interior & Exterior', body: 'Complete painting services inside and out.' },
    ],
    reviewSnippets: [
      'Our house looks brand new. Clean work and beautiful results.',
      'Professional crew, great color advice, and they finished on schedule.',
      'Best painters we have ever hired. Highly recommend to everyone.',
    ],
  },
  remodeling: {
    aboutEyebrow: 'CRAFTSMANSHIP',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Homeowners Trust Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE BUILD',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'PROJECT FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Your Dream Renovation Starts Here',
    ctaText: 'Free consultation and detailed project estimate.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Custom Designs', 'On-Time Completion', 'Warranty Backed'],
    whyCards: [
      { title: 'Expert Craftsmen', body: 'Skilled tradespeople who take pride in every detail.' },
      { title: 'Custom Design', body: 'We bring your vision to life, tailored to your space.' },
      { title: 'On-Time & On-Budget', body: 'Transparent timelines and pricing you can count on.' },
      { title: 'Quality Materials', body: 'Premium materials that stand the test of time.' },
      { title: 'Full-Service', body: 'From design to permit to final walkthrough.' },
      { title: 'Satisfaction Guaranteed', body: 'We do not finish until you are thrilled.' },
    ],
    reviewSnippets: [
      'They transformed our kitchen beyond what we imagined. Incredible craftsmanship.',
      'On time, on budget, and the quality is outstanding. Could not be happier.',
      'From concept to completion, they made the entire process stress-free.',
    ],
  },
  handyman: {
    aboutEyebrow: 'FIX IT RIGHT',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Homeowners Call Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE FIX',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'One Call Fixes It All',
    ctaText: 'No job too small — affordable handyman services.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Insured', 'No Job Too Small', 'Honest Pricing', 'Locally Owned'],
    whyCards: [
      { title: 'Multi-Skilled', body: 'One call for plumbing, electrical, carpentry, and more.' },
      { title: 'Honest Pricing', body: 'Flat-rate quotes with no hidden fees.' },
      { title: 'Reliable & Punctual', body: 'We show up on time and get it done right.' },
      { title: 'Locally Owned', body: 'Your neighbor, not a national franchise.' },
      { title: 'No Job Too Small', body: 'From leaky faucets to drywall patches.' },
      { title: 'Clean & Respectful', body: 'We treat your home like our own.' },
    ],
    reviewSnippets: [
      'Fixed everything on our list in one visit. Fair prices and great work.',
      'Reliable, honest, and skilled. Our go-to handyman for everything.',
      'Showed up on time, did quality work, and cleaned up after. Perfect.',
    ],
  },
  pest_control: {
    aboutEyebrow: 'PEST FREE',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Homeowners Trust Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE TREAT',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Pest Problems? We Handle It.',
    ctaText: 'Free inspection — safe treatments for your family and pets.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Eco-Friendly Options', 'Same-Day Service', 'Satisfaction Guaranteed'],
    whyCards: [
      { title: 'Licensed Technicians', body: 'State-certified pest control professionals.' },
      { title: 'Family & Pet Safe', body: 'EPA-approved treatments that are safe for your home.' },
      { title: 'Same-Day Service', body: 'Fast response when pests cannot wait.' },
      { title: 'Prevention Plans', body: 'Ongoing protection to keep pests out for good.' },
      { title: 'All Pest Types', body: 'Termites, rodents, roaches, ants, mosquitoes, and more.' },
      { title: 'Satisfaction Guaranteed', body: 'If pests come back, so do we — free of charge.' },
    ],
    reviewSnippets: [
      'Eliminated our ant problem completely. Professional and thorough.',
      'Safe, effective, and they took the time to explain everything.',
      'We have been pest-free ever since. Best service in the area.',
    ],
  },
  pressure_washing: {
    aboutEyebrow: 'CLEAN SURFACES',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Property Owners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE CLEAN',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Restore Your Property\'s Curb Appeal',
    ctaText: 'Free estimate — driveways, siding, decks, and more.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Insured', 'Eco-Friendly', 'Free Estimates', 'Residential & Commercial'],
    whyCards: [
      { title: 'Professional Equipment', body: 'Commercial-grade pressure washers for every surface.' },
      { title: 'Surface Safe', body: 'We adjust pressure and technique for each material.' },
      { title: 'Eco-Friendly', body: 'Biodegradable cleaning solutions that protect the environment.' },
      { title: 'Fast Turnaround', body: 'Most jobs completed in a single visit.' },
      { title: 'Curb Appeal', body: 'Instantly refresh the look of your property.' },
      { title: 'Satisfaction Guaranteed', body: 'Not clean enough? We will come back.' },
    ],
    reviewSnippets: [
      'Our driveway looks brand new. Incredible difference in just a few hours.',
      'Professional, fast, and the results were better than expected.',
      'They cleaned our entire house exterior and it looks like a new paint job.',
    ],
  },
  garage_door: {
    aboutEyebrow: 'TRUSTED LOCALLY',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Homeowners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE DO',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Garage Door Issues? Call Now.',
    ctaText: 'Same-day repair and installation — free estimates.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Same-Day Service', 'All Brands', 'Warranty Backed'],
    whyCards: [
      { title: 'Fast Response', body: 'Same-day service for broken springs, openers, and panels.' },
      { title: 'All Brands Serviced', body: 'We repair and install every major garage door brand.' },
      { title: 'Upfront Pricing', body: 'Clear quotes before any work begins.' },
      { title: 'Quality Parts', body: 'Premium replacement parts that last.' },
      { title: 'Safety First', body: 'Proper installation and safety inspections every time.' },
      { title: 'Satisfaction Guaranteed', body: 'We stand behind our work with a written warranty.' },
    ],
    reviewSnippets: [
      'Fixed our broken spring in under an hour. Professional and affordable.',
      'New garage door installed perfectly. The crew was fast and courteous.',
      'Called in the morning, fixed by afternoon. Great service.',
    ],
  },
  gutters: {
    aboutEyebrow: 'TRUSTED LOCALLY',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Homeowners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE DO',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Protect Your Home From Water Damage',
    ctaText: 'Gutter installation, repair, and cleaning — free estimates.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Free Estimates', 'Seamless Gutters', 'Warranty Backed'],
    whyCards: [
      { title: 'Expert Installation', body: 'Custom-fit seamless gutters for your home.' },
      { title: 'Thorough Cleaning', body: 'Complete gutter cleaning with full inspection.' },
      { title: 'Gutter Guards', body: 'Leaf protection systems that reduce maintenance.' },
      { title: 'Damage Prevention', body: 'Protect your foundation, siding, and landscaping.' },
      { title: 'Fair Pricing', body: 'Honest quotes with no hidden fees.' },
      { title: 'Quality Materials', body: 'Durable aluminum and copper options available.' },
    ],
    reviewSnippets: [
      'New gutters look great and work perfectly. Professional installation.',
      'Cleaned and repaired our gutters quickly. No more overflow issues.',
      'Fair price, quality materials, and the crew was respectful of our property.',
    ],
  },
  flooring: {
    aboutEyebrow: 'FROM THE GROUND UP',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Homeowners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE INSTALL',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Beautiful Floors Start Here',
    ctaText: 'Free in-home consultation and estimate.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Free Estimates', 'Premium Materials', 'Clean Installation'],
    whyCards: [
      { title: 'Expert Installers', body: 'Skilled craftsmen with years of flooring experience.' },
      { title: 'Premium Selection', body: 'Hardwood, tile, vinyl, laminate, and carpet options.' },
      { title: 'Clean Installation', body: 'We protect your home and leave it spotless.' },
      { title: 'Honest Pricing', body: 'No surprises — detailed quotes up front.' },
      { title: 'On-Time Completion', body: 'Projects completed on schedule, every time.' },
      { title: 'Warranty Backed', body: 'Installation backed by our workmanship guarantee.' },
    ],
    reviewSnippets: [
      'Beautiful hardwood floors installed perfectly. The team was meticulous.',
      'Fair pricing, fast installation, and the floors look stunning.',
      'They helped us choose the perfect flooring and installed it flawlessly.',
    ],
  },
  concrete: {
    aboutEyebrow: 'SOLID FOUNDATIONS',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Property Owners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE BUILD',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Strong Foundations. Lasting Results.',
    ctaText: 'Free estimates on driveways, patios, foundations, and more.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Free Estimates', 'Residential & Commercial', 'Quality Guaranteed'],
    whyCards: [
      { title: 'Expert Crews', body: 'Experienced concrete professionals on every pour.' },
      { title: 'Quality Mix', body: 'Premium concrete mixes for durability and finish.' },
      { title: 'On-Time Delivery', body: 'Projects completed within the agreed timeline.' },
      { title: 'Custom Finishes', body: 'Stamped, stained, exposed aggregate, and polished.' },
      { title: 'Structural Integrity', body: 'Proper reinforcement and drainage for every job.' },
      { title: 'Fair Pricing', body: 'Detailed estimates with no hidden costs.' },
    ],
    reviewSnippets: [
      'Our new driveway looks incredible. Smooth finish and perfectly level.',
      'Professional crew, quality work, and they cleaned up everything after.',
      'Best concrete work in the area. The patio turned out beautifully.',
    ],
  },
  fencing: {
    aboutEyebrow: 'BOUNDARY EXPERTS',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Property Owners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE BUILD',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Define Your Property. Protect What Matters.',
    ctaText: 'Free estimates on wood, vinyl, chain-link, and iron fencing.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Free Estimates', 'All Fence Types', 'Warranty Backed'],
    whyCards: [
      { title: 'Expert Installation', body: 'Professional fence builders with attention to detail.' },
      { title: 'All Fence Types', body: 'Wood, vinyl, chain-link, iron, and composite options.' },
      { title: 'Custom Designs', body: 'Fences tailored to your property and style.' },
      { title: 'Permit Assistance', body: 'We handle local codes and permit requirements.' },
      { title: 'Fast Installation', body: 'Most residential fences completed in 1-2 days.' },
      { title: 'Built to Last', body: 'Quality materials and proper post-setting techniques.' },
    ],
    reviewSnippets: [
      'Beautiful fence installed in just two days. Looks perfect.',
      'Professional crew, quality materials, and a fair price. Very happy.',
      'They handled the permit and installed a gorgeous cedar fence.',
    ],
  },
  restoration: {
    aboutEyebrow: 'DAMAGE EXPERTS',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Property Owners Trust Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE RESTORE',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Disaster Strikes. We Respond.',
    ctaText: '24/7 emergency response — water, fire, and mold restoration.',
    packageLabel: 'Your Website Package',
    trustBadges: ['24/7 Emergency', 'IICRC Certified', 'Insurance Direct', 'Full Restoration'],
    whyCards: [
      { title: 'Rapid Response', body: '24/7 emergency crews ready when disaster strikes.' },
      { title: 'IICRC Certified', body: 'Industry-certified restoration technicians.' },
      { title: 'Insurance Assistance', body: 'We work directly with your insurance company.' },
      { title: 'Full Restoration', body: 'From mitigation to rebuild — all under one roof.' },
      { title: 'Advanced Equipment', body: 'Commercial-grade drying, extraction, and remediation.' },
      { title: 'Compassionate Service', body: 'We understand the stress and guide you through it.' },
    ],
    reviewSnippets: [
      'They responded within an hour and had the situation under control fast.',
      'Handled our insurance claim and restored our home beautifully.',
      'Professional, compassionate, and thorough. We could not have asked for better.',
    ],
  },
  moving: {
    aboutEyebrow: 'MOVING MADE EASY',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Families Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'HOW WE HELP',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Your Next Move Starts Here',
    ctaText: 'Free in-home estimate — local and long-distance moves.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Free Estimates', 'No Hidden Fees', 'Careful Handling'],
    whyCards: [
      { title: 'Professional Movers', body: 'Trained crews who handle your belongings with care.' },
      { title: 'Transparent Pricing', body: 'Flat-rate quotes with no surprise charges.' },
      { title: 'On-Time Arrivals', body: 'We show up when we say we will.' },
      { title: 'Full-Service Options', body: 'Packing, loading, transport, and unpacking available.' },
      { title: 'Local & Long Distance', body: 'We handle moves of every size and distance.' },
      { title: 'Damage Protection', body: 'Blankets, padding, and insurance coverage included.' },
    ],
    reviewSnippets: [
      'Smooth move from start to finish. The crew was fast and careful.',
      'Best movers we have ever used. On time, fair price, and nothing damaged.',
      'They packed everything perfectly and had us settled in by afternoon.',
    ],
  },
  junk_removal: {
    aboutEyebrow: 'CLUTTER FREE',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Customers Call Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE HAUL',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Junk Gone. Space Reclaimed.',
    ctaText: 'Same-day pickup — we do the heavy lifting.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Same-Day Service', 'Upfront Pricing', 'Eco-Friendly Disposal', 'Insured'],
    whyCards: [
      { title: 'Same-Day Pickup', body: 'Call now, junk gone today.' },
      { title: 'Upfront Pricing', body: 'You know the price before we load a single item.' },
      { title: 'We Do the Work', body: 'Our crew handles all the heavy lifting.' },
      { title: 'Eco-Friendly', body: 'We donate and recycle whenever possible.' },
      { title: 'Any Size Job', body: 'Single items to full property cleanouts.' },
      { title: 'Respectful Crew', body: 'Professional, uniformed, and courteous.' },
    ],
    reviewSnippets: [
      'Called in the morning, junk was gone by lunch. Easy and affordable.',
      'They hauled away years of clutter and left the garage spotless.',
      'Great price, fast service, and the crew was super friendly.',
    ],
  },
  pool: {
    aboutEyebrow: 'POOL PROS',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Pool Owners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE DO',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Crystal Clear Water All Season',
    ctaText: 'Weekly service plans and one-time cleanings available.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Certified Technicians', 'Weekly Plans', 'Equipment Repair'],
    whyCards: [
      { title: 'Certified Technicians', body: 'CPO-certified pool professionals.' },
      { title: 'Balanced Chemistry', body: 'Crystal clear water with perfect chemical balance.' },
      { title: 'Equipment Repair', body: 'Pumps, filters, heaters, and automation systems.' },
      { title: 'Weekly Service', body: 'Worry-free maintenance plans for busy homeowners.' },
      { title: 'Pool Renovation', body: 'Resurfacing, tile, decking, and remodels.' },
      { title: 'Honest Pricing', body: 'No contracts required. Transparent pricing.' },
    ],
    reviewSnippets: [
      'Our pool has never looked better. Consistent, reliable weekly service.',
      'Fixed our pump issue quickly and saved us from a costly replacement.',
      'Professional, knowledgeable, and always on schedule. Highly recommend.',
    ],
  },
  solar: {
    aboutEyebrow: 'CLEAN ENERGY',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Homeowners Go Solar With Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE OFFER',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'SOLAR FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Power Your Home With the Sun',
    ctaText: 'Free solar assessment and savings estimate.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', 'Free Assessment', 'Financing Available', '25-Year Warranty'],
    whyCards: [
      { title: 'Expert Installation', body: 'NABCEP-certified solar installers.' },
      { title: 'Lower Bills', body: 'Cut your electricity costs from day one.' },
      { title: 'Financing Options', body: '$0 down plans that make solar affordable.' },
      { title: 'Quality Panels', body: 'Tier-1 panels with 25-year performance warranty.' },
      { title: 'Battery Storage', body: 'Backup power for outages and peak demand.' },
      { title: 'Full Monitoring', body: 'Track your production and savings in real time.' },
    ],
    reviewSnippets: [
      'Our electric bill dropped by 80% in the first month. Amazing.',
      'Professional installation and the system has been flawless ever since.',
      'They walked us through everything and made the process simple.',
    ],
  },
  security: {
    aboutEyebrow: 'PROTECTION FIRST',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Homeowners Trust Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE PROTECT',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Protect What Matters Most',
    ctaText: 'Free security assessment for your home or business.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Insured', '24/7 Monitoring', 'Smart Home Ready', 'Free Assessment'],
    whyCards: [
      { title: '24/7 Monitoring', body: 'Round-the-clock professional monitoring.' },
      { title: 'Smart Integration', body: 'Control your system from your phone anywhere.' },
      { title: 'Custom Design', body: 'Systems designed specifically for your property.' },
      { title: 'Professional Install', body: 'Expert installation with no DIY guesswork.' },
      { title: 'Fast Response', body: 'Immediate alerts to you and local authorities.' },
      { title: 'No Long Contracts', body: 'Flexible plans without long-term commitments.' },
    ],
    reviewSnippets: [
      'Peace of mind knowing our home is protected 24/7. Great system.',
      'Easy to use app and the installation was quick and professional.',
      'They designed a custom system that covers every angle of our property.',
    ],
  },
  accounting: {
    aboutEyebrow: 'YOUR FINANCES',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Clients Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'HOW WE HELP',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Get Your Finances in Order',
    ctaText: 'Free initial consultation for new clients.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed CPA', 'Year-Round Service', 'Small Business Experts', 'Confidential'],
    whyCards: [
      { title: 'Licensed CPAs', body: 'Credentialed professionals you can trust with your finances.' },
      { title: 'Tax Expertise', body: 'Maximize deductions and minimize liability.' },
      { title: 'Year-Round Service', body: 'Proactive guidance, not just April deadlines.' },
      { title: 'Small Business Focus', body: 'Tailored solutions for growing businesses.' },
      { title: 'Clear Communication', body: 'We explain your finances in plain language.' },
      { title: 'Confidential & Secure', body: 'Your financial data is always protected.' },
    ],
    reviewSnippets: [
      'They saved us thousands on our taxes. Knowledgeable and responsive.',
      'Clear communication and proactive advice. Best accountant we have had.',
      'Finally found a CPA who actually explains things in plain English.',
    ],
  },
  insurance: {
    aboutEyebrow: 'YOUR COVERAGE',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Clients Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE COVER',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Get the Coverage You Deserve',
    ctaText: 'Free quote — home, auto, life, and business insurance.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Independent Agent', 'Multiple Carriers', 'Free Quotes', 'Claims Assistance'],
    whyCards: [
      { title: 'Independent Agent', body: 'We shop multiple carriers to find you the best rate.' },
      { title: 'Personalized Coverage', body: 'Plans tailored to your specific needs and budget.' },
      { title: 'Claims Support', body: 'We advocate for you when it matters most.' },
      { title: 'All Coverage Types', body: 'Home, auto, life, business, and specialty insurance.' },
      { title: 'Annual Reviews', body: 'We review your policy each year to ensure best value.' },
      { title: 'Local & Accessible', body: 'A real person answers when you call.' },
    ],
    reviewSnippets: [
      'Saved us hundreds by shopping multiple carriers. Great service.',
      'When we had a claim, they were right there guiding us through it.',
      'Personal service you just cannot get from the big national companies.',
    ],
  },
  real_estate: {
    aboutEyebrow: 'YOUR HOME',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Buyers & Sellers Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'HOW WE HELP',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Your Dream Home Is Closer Than You Think',
    ctaText: 'Free market analysis for buyers and sellers.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed Agent', 'Local Expert', 'Free Market Analysis', 'Negotiation Experts'],
    whyCards: [
      { title: 'Local Market Expert', body: 'Deep knowledge of neighborhoods, pricing, and trends.' },
      { title: 'Strong Negotiator', body: 'We fight to get you the best deal possible.' },
      { title: 'Full-Service Support', body: 'From first showing to closing day and beyond.' },
      { title: 'Marketing Expertise', body: 'Professional photos, staging, and digital marketing.' },
      { title: 'Transparent Process', body: 'Clear communication at every step of the transaction.' },
      { title: 'Client First', body: 'Your goals drive every decision we make.' },
    ],
    reviewSnippets: [
      'Found us our dream home and negotiated an incredible price. The best.',
      'Sold our house in under a week for above asking. Amazing marketing.',
      'Patient, knowledgeable, and always available. Made the process seamless.',
    ],
  },
  financial_services: {
    aboutEyebrow: 'YOUR FUTURE',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Clients Trust Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'HOW WE HELP',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Secure Your Financial Future',
    ctaText: 'Free consultation — retirement, investments, and planning.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Fiduciary Duty', 'Personalized Plans', 'Transparent Fees', 'Experienced Advisors'],
    whyCards: [
      { title: 'Fiduciary Standard', body: 'We always act in your best interest — legally bound.' },
      { title: 'Personalized Plans', body: 'Custom strategies based on your goals and timeline.' },
      { title: 'Transparent Fees', body: 'No hidden costs — you know exactly what you pay.' },
      { title: 'Retirement Planning', body: 'Comprehensive plans for a comfortable retirement.' },
      { title: 'Investment Management', body: 'Diversified portfolios aligned with your risk tolerance.' },
      { title: 'Ongoing Support', body: 'Regular reviews and adjustments as life changes.' },
    ],
    reviewSnippets: [
      'Finally feel confident about our retirement plan. Outstanding guidance.',
      'Transparent, patient, and genuinely invested in our financial well-being.',
      'They simplified our finances and put us on a clear path forward.',
    ],
  },
  photography: {
    aboutEyebrow: 'OUR LENS',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Clients Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE CAPTURE',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'BOOKING FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Capture Your Story',
    ctaText: 'Book your session today — limited availability.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Professional Equipment', 'Fast Turnaround', 'Custom Editing', 'Satisfaction Guaranteed'],
    whyCards: [
      { title: 'Professional Equipment', body: 'Top-tier cameras and lighting for every session.' },
      { title: 'Artistic Vision', body: 'A creative eye that captures genuine moments.' },
      { title: 'Fast Delivery', body: 'Edited photos delivered within one week.' },
      { title: 'Flexible Locations', body: 'Studio, on-location, or destination shoots.' },
      { title: 'Custom Editing', body: 'Professional retouching included with every package.' },
      { title: 'Print Options', body: 'Gallery-quality prints, canvases, and albums.' },
    ],
    reviewSnippets: [
      'The photos were absolutely stunning. Captured every special moment perfectly.',
      'Professional, creative, and made everyone feel comfortable. Highly recommend.',
      'Best photographer we have ever worked with. The images are breathtaking.',
    ],
  },
  chiropractic: {
    aboutEyebrow: 'YOUR WELLNESS',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Patients Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'HOW WE HELP',
    reviewsLabel: 'Patient Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'PATIENT FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Live Without Pain',
    ctaText: 'New patient special — comprehensive exam and consultation.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed Doctor', 'Gentle Techniques', 'Insurance Accepted', 'Same-Day Appointments'],
    whyCards: [
      { title: 'Licensed Chiropractor', body: 'Doctor of Chiropractic with extensive training.' },
      { title: 'Gentle Techniques', body: 'Adjustments tailored to your comfort level.' },
      { title: 'Whole-Body Approach', body: 'We treat the root cause, not just the symptoms.' },
      { title: 'Insurance Friendly', body: 'We accept most major insurance plans.' },
      { title: 'Fast Relief', body: 'Many patients feel better after their first visit.' },
      { title: 'Personalized Care', body: 'Treatment plans designed around your specific needs.' },
    ],
    reviewSnippets: [
      'After years of back pain, I finally found relief. Life-changing care.',
      'Gentle, thorough, and genuinely caring. The best chiropractor in town.',
      'They took the time to understand my issues and created a real plan.',
    ],
  },
  physical_therapy: {
    aboutEyebrow: 'YOUR RECOVERY',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Patients Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'HOW WE HELP',
    reviewsLabel: 'Patient Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'PATIENT FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Get Back to Doing What You Love',
    ctaText: 'Schedule your evaluation — most insurances accepted.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed Therapists', 'One-on-One Care', 'Insurance Accepted', 'Evidence-Based'],
    whyCards: [
      { title: 'Licensed Therapists', body: 'Doctoral-level physical therapists.' },
      { title: 'One-on-One Sessions', body: 'Dedicated attention for every visit.' },
      { title: 'Evidence-Based', body: 'Treatments grounded in the latest research.' },
      { title: 'Custom Plans', body: 'Individualized programs for your specific condition.' },
      { title: 'Sports Rehab', body: 'Get athletes back to peak performance safely.' },
      { title: 'Insurance Accepted', body: 'We work with most major insurance providers.' },
    ],
    reviewSnippets: [
      'After surgery, they got me back on my feet faster than expected.',
      'The one-on-one attention here is incredible. My therapist knows my case inside out.',
      'Best PT clinic in the area. Patient, knowledgeable, and results-focused.',
    ],
  },
  counseling: {
    aboutEyebrow: 'YOUR WELL-BEING',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Clients Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'HOW WE HELP',
    reviewsLabel: 'Client Feedback',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'You Do Not Have to Face This Alone',
    ctaText: 'Confidential consultation — in-person and telehealth available.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed Therapists', 'Confidential', 'Insurance Accepted', 'Telehealth Available'],
    whyCards: [
      { title: 'Licensed Counselors', body: 'Credentialed professionals with specialized training.' },
      { title: 'Safe Space', body: 'A confidential, judgment-free environment.' },
      { title: 'Flexible Options', body: 'In-person, video, and phone sessions available.' },
      { title: 'Evidence-Based', body: 'Approaches grounded in clinical research.' },
      { title: 'Insurance Accepted', body: 'We work with most major insurance plans.' },
      { title: 'All Ages', body: 'Individual, couples, family, and youth counseling.' },
    ],
    reviewSnippets: [
      'A safe, supportive space where I finally felt heard. Truly grateful.',
      'The therapist helped me develop real coping strategies that work.',
      'Flexible scheduling and telehealth made it easy to stay consistent.',
    ],
  },
  veterinary: {
    aboutEyebrow: 'PET CARE',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Pet Owners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'HOW WE HELP',
    reviewsLabel: 'Pet Parent Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'PET OWNER FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Compassionate Care for Your Best Friend',
    ctaText: 'New patients welcome — schedule your pet\'s visit today.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed Veterinarians', 'Compassionate Care', 'Modern Facility', 'Emergency Available'],
    whyCards: [
      { title: 'Licensed Veterinarians', body: 'Experienced doctors who genuinely love animals.' },
      { title: 'Compassionate Care', body: 'Gentle handling and stress-free visits.' },
      { title: 'Modern Facility', body: 'State-of-the-art diagnostics and treatment.' },
      { title: 'Preventive Care', body: 'Vaccines, wellness exams, and dental cleanings.' },
      { title: 'Surgery & Urgent Care', body: 'Advanced surgical capabilities when needed.' },
      { title: 'Friendly Staff', body: 'A team that treats every pet like family.' },
    ],
    reviewSnippets: [
      'The vet and staff treat our dog like their own. Wonderful care.',
      'Modern facility, gentle handling, and they always explain everything clearly.',
      'Best vet we have ever had. Our pets actually like going there.',
    ],
  },
  salon: {
    aboutEyebrow: 'BEAUTY & STYLE',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Clients Love Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE OFFER',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'BOOKING FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Look Your Best. Feel Your Best.',
    ctaText: 'Book your appointment today — walk-ins welcome.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed Stylists', 'Premium Products', 'Walk-Ins Welcome', 'Relaxing Atmosphere'],
    whyCards: [
      { title: 'Licensed Stylists', body: 'Experienced professionals who stay on-trend.' },
      { title: 'Premium Products', body: 'We use only salon-grade, professional products.' },
      { title: 'Relaxing Atmosphere', body: 'A space designed for your comfort and enjoyment.' },
      { title: 'Consultations', body: 'Every visit starts with understanding your vision.' },
      { title: 'Walk-Ins Welcome', body: 'No appointment? No problem.' },
      { title: 'Color Specialists', body: 'Expert colorists for highlights, balayage, and more.' },
    ],
    reviewSnippets: [
      'Best haircut I have ever had. The stylist really listened to what I wanted.',
      'Relaxing atmosphere and incredible talent. My new go-to salon.',
      'Color came out exactly as I hoped. Professional and friendly team.',
    ],
  },
  barber: {
    aboutEyebrow: 'THE SHOP',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Guys Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE OFFER',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'WALK-IN FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'The Best Cut in Town',
    ctaText: 'Walk-ins welcome — appointments available.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed Barbers', 'Walk-Ins Welcome', 'Hot Towel Service', 'Classic & Modern Cuts'],
    whyCards: [
      { title: 'Skilled Barbers', body: 'Classically trained with modern technique.' },
      { title: 'Walk-Ins Welcome', body: 'No appointment needed — just stop by.' },
      { title: 'Hot Towel Service', body: 'The full barbershop experience, every visit.' },
      { title: 'All Styles', body: 'Fades, tapers, beard trims, and classic cuts.' },
      { title: 'Relaxed Vibe', body: 'A laid-back shop where you can kick back.' },
      { title: 'Consistent Quality', body: 'The same great cut, every time.' },
    ],
    reviewSnippets: [
      'Best barbershop in the area. Clean fades and a great atmosphere.',
      'Walk in, sit down, walk out looking sharp. Simple as that.',
      'The hot towel shave is amazing. Old-school barbershop done right.',
    ],
  },
  nails: {
    aboutEyebrow: 'NAIL ART',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Clients Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE OFFER',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'BOOKING FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Treat Yourself to Beautiful Nails',
    ctaText: 'Walk-ins welcome — appointments recommended for weekends.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed Technicians', 'Sanitized Tools', 'Walk-Ins Welcome', 'Gel & Acrylic'],
    whyCards: [
      { title: 'Licensed Technicians', body: 'Skilled nail artists with attention to detail.' },
      { title: 'Hygiene First', body: 'Hospital-grade sterilization of all tools.' },
      { title: 'Trendy Designs', body: 'From classic French tips to custom nail art.' },
      { title: 'Quality Products', body: 'OPI, Essie, and premium gel brands.' },
      { title: 'Relaxing Experience', body: 'Spa chairs and a calming atmosphere.' },
      { title: 'Affordable Luxury', body: 'Beautiful nails without the boutique price tag.' },
    ],
    reviewSnippets: [
      'The cleanest nail salon I have ever been to. Beautiful work every time.',
      'My nails lasted three weeks without a single chip. Incredible quality.',
      'Friendly staff, relaxing environment, and the designs are always perfect.',
    ],
  },
  beauty: {
    aboutEyebrow: 'GLOW UP',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Clients Love Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE OFFER',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'BOOKING FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Reveal Your Natural Beauty',
    ctaText: 'Book your treatment today — new client specials available.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed Estheticians', 'Premium Products', 'Relaxing Spa', 'Results Driven'],
    whyCards: [
      { title: 'Licensed Estheticians', body: 'Certified skincare professionals.' },
      { title: 'Premium Products', body: 'Medical-grade and luxury skincare lines.' },
      { title: 'Spa Environment', body: 'A tranquil space designed for relaxation.' },
      { title: 'Custom Treatments', body: 'Personalized plans for your skin type.' },
      { title: 'Advanced Technology', body: 'LED therapy, microneedling, and more.' },
      { title: 'Visible Results', body: 'Treatments that deliver real, lasting improvement.' },
    ],
    reviewSnippets: [
      'My skin has never looked this good. The facials here are incredible.',
      'Relaxing atmosphere and the esthetician really knows her stuff.',
      'Visible improvement after just two treatments. Worth every penny.',
    ],
  },
  sushi: {
    aboutEyebrow: 'CRAFT & TRADITION',
    whyEyebrow: 'THE EXPERIENCE',
    whyHeadline: 'Why Guests Return',
    servicesLabel: 'Our Menu',
    servicesEyebrow: 'FRESH DAILY',
    reviewsLabel: 'Guest Reviews',
    reviewsEyebrow: 'WHAT GUESTS SAY',
    faqEyebrow: 'BEFORE YOUR VISIT',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Experience Sushi at Its Finest',
    ctaText: 'Reservations recommended — walk-ins welcome.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Fresh Daily', 'Master Chef', 'Omakase Available', 'BYOB Friendly'],
    whyCards: [
      { title: 'Fresh Daily', body: 'Fish sourced and prepared fresh every single day.' },
      { title: 'Master Chef', body: 'Classically trained sushi chefs with decades of skill.' },
      { title: 'Omakase Experience', body: 'Let the chef curate your perfect meal.' },
      { title: 'Elegant Atmosphere', body: 'A dining space designed for memorable evenings.' },
      { title: 'Premium Sake', body: 'Curated sake and beverage pairings.' },
      { title: 'Private Dining', body: 'Intimate rooms for special occasions.' },
    ],
    reviewSnippets: [
      'The freshest sushi I have ever had outside Japan. Absolutely stunning.',
      'The omakase experience was unforgettable. Every course was a masterpiece.',
      'Elegant atmosphere, incredible fish, and impeccable service.',
    ],
  },
  pizza: {
    aboutEyebrow: 'BRICK OVEN',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Customers Love Us',
    servicesLabel: 'Our Menu',
    servicesEyebrow: 'FRESH FROM THE OVEN',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'WHAT PEOPLE SAY',
    faqEyebrow: 'ORDER FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Real Pizza. Real Ingredients.',
    ctaText: 'Order online or call for pickup and delivery.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Fresh Dough Daily', 'Local Ingredients', 'Fast Delivery', 'Family Recipes'],
    whyCards: [
      { title: 'Fresh Dough Daily', body: 'Made from scratch every single morning.' },
      { title: 'Quality Ingredients', body: 'Premium cheeses, house-made sauce, and fresh toppings.' },
      { title: 'Fast Delivery', body: 'Hot pizza to your door in 30 minutes or less.' },
      { title: 'Family Recipes', body: 'Passed-down recipes that have stood the test of time.' },
      { title: 'Catering Available', body: 'Feed the whole party with our catering packages.' },
      { title: 'Dine-In Welcome', body: 'A warm, family-friendly dining room.' },
    ],
    reviewSnippets: [
      'Best pizza in town, hands down. The crust is perfection.',
      'Fresh ingredients, generous portions, and always delivered hot.',
      'Our family has been ordering here for years. Consistently amazing.',
    ],
  },
  bakery: {
    aboutEyebrow: 'BAKED FRESH',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Customers Love Us',
    servicesLabel: 'Our Offerings',
    servicesEyebrow: 'FRESH FROM THE OVEN',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'WHAT PEOPLE SAY',
    faqEyebrow: 'ORDER FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Made From Scratch. Made With Love.',
    ctaText: 'Order your custom cake or stop by for fresh-baked treats.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Baked Fresh Daily', 'Custom Cakes', 'Local Ingredients', 'Special Orders Welcome'],
    whyCards: [
      { title: 'Baked Fresh Daily', body: 'Everything made from scratch each morning.' },
      { title: 'Custom Cakes', body: 'Beautifully designed cakes for any occasion.' },
      { title: 'Quality Ingredients', body: 'Real butter, farm eggs, and premium flour.' },
      { title: 'Special Dietary Options', body: 'Gluten-free, vegan, and allergy-friendly items.' },
      { title: 'Catering & Events', body: 'Pastry platters and dessert bars for any event.' },
      { title: 'Community Favorite', body: 'A neighborhood staple for years.' },
    ],
    reviewSnippets: [
      'The best croissants outside of Paris. Everything here is perfection.',
      'Our wedding cake was absolutely stunning and tasted even better.',
      'Fresh, beautiful, and worth every calorie. A true neighborhood gem.',
    ],
  },
  catering: {
    aboutEyebrow: 'EVENT DINING',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Event Planners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE SERVE',
    reviewsLabel: 'Client Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'EVENT FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Unforgettable Events Start With Great Food',
    ctaText: 'Free tasting for events over 50 guests.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Full-Service Catering', 'Custom Menus', 'Professional Staff', 'Events of All Sizes'],
    whyCards: [
      { title: 'Custom Menus', body: 'Menus designed around your event and dietary needs.' },
      { title: 'Professional Staff', body: 'Trained servers, bartenders, and event coordinators.' },
      { title: 'Setup & Cleanup', body: 'We handle everything so you can enjoy your event.' },
      { title: 'All Event Sizes', body: 'From intimate dinners to large corporate events.' },
      { title: 'Fresh & Local', body: 'Seasonal ingredients sourced from local purveyors.' },
      { title: 'Reliable Service', body: 'On-time delivery and flawless execution.' },
    ],
    reviewSnippets: [
      'The food was the highlight of our wedding. Every guest raved about it.',
      'Professional, punctual, and the menu was customized perfectly.',
      'They made our corporate event feel effortless. Incredible food and service.',
    ],
  },
  coffee: {
    aboutEyebrow: 'CRAFTED DAILY',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Coffee Lovers Choose Us',
    servicesLabel: 'Our Menu',
    servicesEyebrow: 'WHAT WE BREW',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'WHAT PEOPLE SAY',
    faqEyebrow: 'FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Life Is Too Short for Bad Coffee',
    ctaText: 'Stop by for your daily brew — locally roasted beans.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Locally Roasted', 'Fair Trade', 'Fresh Pastries', 'Free WiFi'],
    whyCards: [
      { title: 'Locally Roasted', body: 'Small-batch roasting for peak freshness and flavor.' },
      { title: 'Skilled Baristas', body: 'Trained professionals who craft every cup with care.' },
      { title: 'Fair Trade Beans', body: 'Ethically sourced from sustainable farms.' },
      { title: 'Cozy Atmosphere', body: 'A welcoming space to work, meet, or relax.' },
      { title: 'Fresh Pastries', body: 'Baked goods made fresh every morning.' },
      { title: 'Community Hub', body: 'More than coffee — a neighborhood gathering place.' },
    ],
    reviewSnippets: [
      'Best coffee in the area. The latte art is almost too pretty to drink.',
      'Cozy atmosphere, friendly baristas, and the pastries are incredible.',
      'My daily ritual. Consistently perfect coffee every single visit.',
    ],
  },
  daycare: {
    aboutEyebrow: 'NURTURING GROWTH',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Parents Choose Us',
    servicesLabel: 'Our Programs',
    servicesEyebrow: 'LEARNING & PLAY',
    reviewsLabel: 'Parent Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'PARENT FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'A Safe, Fun Place to Learn and Grow',
    ctaText: 'Schedule a tour — enrollment open now.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Licensed & Certified', 'Low Ratios', 'Safe & Clean', 'Curriculum Based'],
    whyCards: [
      { title: 'Licensed Caregivers', body: 'CPR-certified, background-checked professionals.' },
      { title: 'Low Child-to-Staff Ratios', body: 'Personalized attention for every child.' },
      { title: 'Age-Appropriate Curriculum', body: 'Structured learning through play and discovery.' },
      { title: 'Safe & Clean', body: 'State-inspected facility with rigorous safety standards.' },
      { title: 'Nutritious Meals', body: 'Healthy snacks and meals included daily.' },
      { title: 'Flexible Hours', body: 'Early drop-off and late pickup available.' },
    ],
    reviewSnippets: [
      'Our daughter thrives here. The teachers genuinely care about every child.',
      'Clean, safe, and educational. The best daycare decision we ever made.',
      'Flexible hours and wonderful staff. Our kids love going every day.',
    ],
  },
  tutoring: {
    aboutEyebrow: 'ACADEMIC SUCCESS',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Students Succeed With Us',
    servicesLabel: 'Our Programs',
    servicesEyebrow: 'HOW WE HELP',
    reviewsLabel: 'Parent & Student Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'ENROLLMENT FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Unlock Your Child\'s Potential',
    ctaText: 'Free assessment — personalized learning plans.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Certified Tutors', 'All Subjects', 'Flexible Scheduling', 'Proven Results'],
    whyCards: [
      { title: 'Certified Tutors', body: 'Qualified educators with subject-matter expertise.' },
      { title: 'Personalized Plans', body: 'Custom learning strategies for each student.' },
      { title: 'All Subjects', body: 'Math, science, reading, writing, and test prep.' },
      { title: 'Flexible Scheduling', body: 'After school, weekends, and online options.' },
      { title: 'Progress Tracking', body: 'Regular reports so parents see real improvement.' },
      { title: 'Confidence Building', body: 'Students gain skills and self-assurance.' },
    ],
    reviewSnippets: [
      'My son went from struggling to honor roll. This program works.',
      'The tutor connected with our daughter in a way her teachers could not.',
      'Flexible scheduling and measurable results. Best investment in education.',
    ],
  },
  auto_detailing: {
    aboutEyebrow: 'SHOWROOM SHINE',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Car Owners Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE DO',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Your Car Deserves Better',
    ctaText: 'Mobile detailing — we come to you.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Mobile Service', 'Eco-Friendly Products', 'Ceramic Coating', 'Satisfaction Guaranteed'],
    whyCards: [
      { title: 'Mobile Service', body: 'We come to your home or office — ultimate convenience.' },
      { title: 'Premium Products', body: 'Professional-grade cleaners and protectants.' },
      { title: 'Attention to Detail', body: 'Every surface cleaned, polished, and protected.' },
      { title: 'Ceramic Coating', body: 'Long-lasting paint protection and shine.' },
      { title: 'Interior Deep Clean', body: 'Seats, carpets, dashboards — spotless inside and out.' },
      { title: 'Eco-Friendly', body: 'Waterless and low-water wash options available.' },
    ],
    reviewSnippets: [
      'My car looks better than the day I bought it. Incredible attention to detail.',
      'The ceramic coating was worth every penny. Still beading water months later.',
      'Convenient mobile service and the results are always showroom quality.',
    ],
  },
  towing: {
    aboutEyebrow: 'ROADSIDE HELP',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Drivers Call Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'HOW WE HELP',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Stuck? We Are On Our Way.',
    ctaText: '24/7 towing and roadside assistance.',
    packageLabel: 'Your Website Package',
    trustBadges: ['24/7 Service', 'Fast Response', 'All Vehicle Types', 'Upfront Pricing'],
    whyCards: [
      { title: '24/7 Availability', body: 'Day or night, we are always ready to help.' },
      { title: 'Fast Response', body: 'Average arrival time under 30 minutes.' },
      { title: 'All Vehicle Types', body: 'Cars, trucks, motorcycles, and heavy equipment.' },
      { title: 'Upfront Pricing', body: 'Clear pricing before we hook up your vehicle.' },
      { title: 'Damage-Free Towing', body: 'Modern equipment that protects your vehicle.' },
      { title: 'Roadside Assistance', body: 'Jump starts, lockouts, tire changes, and fuel delivery.' },
    ],
    reviewSnippets: [
      'They arrived in 20 minutes at midnight. Professional and affordable.',
      'Careful with my car and the price was exactly what they quoted.',
      'Best towing service in the area. Fast, honest, and reliable.',
    ],
  },
  retail: {
    aboutEyebrow: 'OUR STORY',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Shoppers Choose Us',
    servicesLabel: 'What We Offer',
    servicesEyebrow: 'IN STORE',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'WHAT PEOPLE SAY',
    faqEyebrow: 'SHOPPING FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Visit Us Today',
    ctaText: 'Shop local — unique finds you will not get anywhere else.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Locally Owned', 'Curated Selection', 'Friendly Staff', 'Easy Returns'],
    whyCards: [
      { title: 'Curated Selection', body: 'Hand-picked products you will not find at big box stores.' },
      { title: 'Knowledgeable Staff', body: 'Real people who know the products and can help.' },
      { title: 'Shop Local', body: 'Support your community by shopping small.' },
      { title: 'Quality Products', body: 'Premium brands and unique finds.' },
      { title: 'Easy Returns', body: 'Hassle-free return and exchange policy.' },
      { title: 'Special Orders', body: 'Cannot find what you need? We will get it for you.' },
    ],
    reviewSnippets: [
      'Great selection and the staff actually knows their products. Refreshing.',
      'Love supporting a local shop with this much character and quality.',
      'Found exactly what I needed and the service was outstanding.',
    ],
  },
  education: {
    aboutEyebrow: 'LEARNING',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Students Choose Us',
    servicesLabel: 'Our Programs',
    servicesEyebrow: 'WHAT WE TEACH',
    reviewsLabel: 'Student & Parent Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'ENROLLMENT FAQ',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Learn Something New Today',
    ctaText: 'Enroll now — classes for all ages and skill levels.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Certified Instructors', 'All Levels', 'Flexible Schedule', 'Small Classes'],
    whyCards: [
      { title: 'Expert Instructors', body: 'Passionate teachers with real-world experience.' },
      { title: 'All Levels', body: 'Beginners to advanced — everyone is welcome.' },
      { title: 'Small Class Sizes', body: 'Personalized attention in every session.' },
      { title: 'Flexible Scheduling', body: 'Daytime, evening, and weekend options.' },
      { title: 'Performance Opportunities', body: 'Recitals, showcases, and exhibitions.' },
      { title: 'Fun & Engaging', body: 'Learning that inspires creativity and confidence.' },
    ],
    reviewSnippets: [
      'The instructor made learning fun and accessible. My daughter loves it.',
      'Great facility, wonderful teachers, and a supportive community.',
      'From beginner to confident in just a few months. Incredible program.',
    ],
  },
  default: {
    aboutEyebrow: 'ABOUT US',
    whyEyebrow: 'THE DIFFERENCE',
    whyHeadline: 'Why Choose Us',
    servicesLabel: 'Our Services',
    servicesEyebrow: 'WHAT WE DO',
    reviewsLabel: 'Customer Reviews',
    reviewsEyebrow: 'TESTIMONIALS',
    faqEyebrow: 'COMMON QUESTIONS',
    faqLabel: 'Frequently Asked Questions',
    ctaHeadline: 'Ready to Get Started?',
    ctaText: 'Contact us today for a free consultation.',
    packageLabel: 'Your Website Package',
    trustBadges: ['Locally Owned', 'Experienced Team', 'Customer Focused', 'Satisfaction Guaranteed'],
    whyCards: [
      { title: 'Experienced Team', body: 'Skilled professionals dedicated to quality work.' },
      { title: 'Reliable Service', body: 'We show up on time and deliver on our promises.' },
      { title: 'Locally Trusted', body: 'Proudly serving our community for years.' },
      { title: 'Satisfaction Guaranteed', body: 'We stand behind everything we do.' },
      { title: 'Transparent Pricing', body: 'Honest quotes with no hidden fees.' },
      { title: 'Customer First', body: 'Your needs drive every decision we make.' },
    ],
    reviewSnippets: [
      'Professional, reliable, and the quality of work was outstanding.',
      'Fair pricing and excellent customer service. Highly recommend.',
      'They went above and beyond our expectations. Will use again.',
    ],
  },
}
